"""create short url

Revision ID: 104e2cf55a2b
Revises: 314eed5c8a1e
Create Date: 2026-04-15 17:25:02.862614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104e2cf55a2b'
down_revision: Union[str, Sequence[str], None] = '314eed5c8a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_url', sa.String(), nullable=True),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.Column('short_code', sa.String(length=12), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_id'), 'short_url', ['id'], unique=False)
    op.create_index(op.f('ix_short_url_main_url'), 'short_url', ['main_url'], unique=False)
    op.create_index(op.f('ix_short_url_short_code'), 'short_url', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_short_code'), table_name='short_url')
    op.drop_index(op.f('ix_short_url_main_url'), table_name='short_url')
    op.drop_index(op.f('ix_short_url_id'), table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###
